_target_: izumi.models.policy.VQBeTPolicy
action_dim: 7
obs_window_size: 3
action_sequence_length: 1
vqvae_n_latent_dims: 512
vqvae_n_embed: 16
vqvae_groups: 2
vqvae_load_dir: null
temperature: 1.0e-6
sequentially_select: true
offset_loss_multiplier: 10.0
secondary_code_multiplier: 0.5
gamma: 2.0
gpt:
  block_size: 50
  input_dim: 256
  n_layer: 6
  n_head: 6
  n_embd: 120
